### ISSUE TITLE
No instructions

### ISSUE THREAD

**Issue by f1ames0ff** [skullernet/openffa#7]
How to build this?

**Comment by Fryziu** [comment]
How to build this with SQLite ?

**Comment by Fryziu** [comment]
> How to build this?

Install gcc, install sqlite3.
install GIT, clone openffa repository.
make clean
make

**Comment by skullernet** [comment]
> How to build this with SQLite ?

Add `CONFIG_SQLITE=y` line to `.config`. Or simply invoke `make CONFIG_SQLITE=y`.

**Comment by f1ames0ff** [comment]
@skullernet no need to necropost

**Comment by skullernet** [comment]
@f1ames0ff can you just fuck off please?
